### ISSUE TITLE
Error given when do is not the last command

### ISSUE THREAD

**Issue by boringblobking** [nuscr/nuscr#144]
Unknown error: Sexplib0__Sexp.Not_found_s(_) was reported for the following program:

global protocol Trick(role N, role E, role S, role W)
{
  PLAY(c:String) from N to T;
    do broadcast(N, E, S, W);

  PLAY(c:String) from E to T;
    do broadcast(N, E, S, W);

  PLAY(c:String) from S to T;
    do broadcast(N, E, S, W);

  PLAY(c:String) from W to T;
    do broadcast(N, E, S, W);
}

global broadcast(role N, role E, role S, role W) 
{
  SHOW(c:String) from T to N;
  SHOW(c:String) from T to E;
  SHOW(c:String) from T to S;
  SHOW(c:String) from T to W;
}

**Comment by fangyi-zhou** [comment]
After the deployment pipeline is completed, you can access the dev version at https://nuscr.dev/nuscr/dev/
