### ISSUE TITLE
Parser broken on master

### ISSUE THREAD

**Issue by fangyi-zhou** [nuscr/nuscr#92]
`git bisect` concluded with the following
commit 24866e34bbcc8972a7aadf39176a215fbbb1282f is the first bad commit
commit 24866e34bbcc8972a7aadf39176a215fbbb1282f
Author: Francisco Ferreira <fferre8@cs.mcgill.ca>
Date:   Sat Jan 11 17:52:19 2020 +0000

    fixed booboo with the lexer

:040000 040000 6da35d87c506e3be4e37263491c39dc97db3e310 e8abe9559cb1980d997d5874b74179eb2e485bac M      examples
:040000 040000 88728a01ec5a13f725a69430ec0c108bf68752cf dbff5003970227484e31813b222c7e2b4dfde016 M      lib

**Comment by fferreira** [comment]
I see, there's a problem with the pragma parser
